dist: xenial
language: rust
rust:
   - 1.33.0
cache: cargo

before_install:
  - openssl aes-256-cbc -K $encrypted_3b7db25add00_key -iv $encrypted_3b7db25add00_iv -in ci/deploy_key.enc -out ci/deploy_key -d
  - chmod 400 ci/deploy_key

install:
  - cargo install mdbook || true

script:
  - ci/build.sh
